name: Auto Assign
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
jobs:
  run:
    runs-on: self-hosted
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: 'Auto-assign issue'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ASSIGNEE: Pixel12pixel
      run: |
        if [ "${{ github.event_name }}" = "issues" ]; then
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/assignees \
          -d '{"assignees": ["'"$ASSIGNEE"'"]}'
        elif [ "${{ github.event_name }}" = "pull_request" ]; then
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/assignees \
          -d '{"assignees": ["'"$ASSIGNEE"'"]}'
        fi
